quarkus:
  application:
    name: home-library-catalog
  http:
    port: 8080
  datasource:
    driver: org.mariadb.jdbc.Driver
    url: ${RDBMS_URL}
    min-size: 5
    max-size: 20
    initial-size: 5
    validation-query-sql: SELECT 1
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PWD}
  hibernate-orm:
    dialect: org.hibernate.dialect.MariaDB103Dialect
    database:
      generation: update
