spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: --APP_NAME--
        resources:
          requests:
            memory: 2Gi
            cpu:    500m
          limits:
            memory: 2Gi
            cpu:    2
